### ISSUE TITLE
two journals merged

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/journalsdb#10]
http://api.journalsdb.org/journals/1083-8791
and 
http://api.journalsdb.org/journals/2666-6367

see 
https://www.sciencedirect.com/journal/transplantation-and-cellular-therapy

so I think the old one should stop having its own issn_l and just be a sub issn of the new one.
that said, can you start an email thread with jason and richard to decide how we'd like journaldb to handle it?

**Comment by caseydm** [comment]
Got it! I'm writing the email but want to think through a couple proposed solutions first.

**Comment by caseydm** [comment]
This is fully implemented now and can be turned on or off with `merge=false` or `merge=true`:

https://api.journalsdb.org/journals/2666-6367
https://api.journalsdb.org/journals/2666-6367?merge=false
https://api.journalsdb.org/journals/1570-9639
