### ISSUE TITLE
is a gold OA journal

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/journalsdb#13]
as per the publisher's website, but we don't list it as one:
https://www.journals.elsevier.com/annals-of-medicine-and-surgery
https://api.journalsdb.org/journals/2049-0801

Guessing this may be because Unpaywall doesn't list it as one (it might have recently flipped).  Can you work with Richard to make sure he either adds it to his Gold OA list manually and then that info makes its way to JournalsDB, or you patch manually and he reads that data from you, or ??  Ditto with all should-be-gold-OA journals you find / we report?  Thanks!

Heather

**Comment by caseydm** [comment]
Got it Heather! I will work this and the previous two issues (APC, Subscription pricing).

**Comment by caseydm** [comment]
Richard was able to update this so it's fixed for this journal. I will keep an eye out for others. Richard had a good point that it would be good to transition the gold OA tracking to journalsdb in the future.

**Comment by hpiwowar** [comment]
Yup sounds good!
Heather

---

Heather Piwowar, cofounder

Our Research <https://ourresearch.org/>: tools to make scholarly research
more open, connected, and reusable
follow at @researchremix <https://twitter.com/researchremix>, @our_research
<https://twitter.com/our_research>, @unpaywall,
<https://twitter.com/unpaywall> and @unsub_org
<https://twitter.com/unsub_org>
