### ISSUE TITLE
missing issn https://api.journalsdb.org/journals/1878-013X

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/journalsdb#14]
Is a little bit of a tricky one because it is used in a bunch of places (Wikipedia, WorldCat) though not sure how official since I think not on Elsevier's page?

Nonetheless I think we should add it as an issn synonym because people have it in their systems (because of WorldCat I bet) and it is clear what it refers to, and redirecting it is helpful for them.

**Comment by caseydm** [comment]
This is fixed! https://api.journalsdb.org/journals/1878-013X
