### ISSUE TITLE
0740-8188 bad title

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/journalsdb#17]
http://api.journalsdb.org/journals/0740-8188

**Comment by caseydm** [comment]
This is fixed. I reviewed all of the mturk modified titles and found seven others similar to this that have been fixed.

**Comment by hpiwowar** [comment]
super thanks!
h

---

Heather Piwowar, cofounder

Our Research <https://ourresearch.org/>: tools to make scholarly research
more open, connected, and reusable
follow at @researchremix <https://twitter.com/researchremix>, @our_research
<https://twitter.com/our_research>, @unpaywall,
<https://twitter.com/unpaywall> and @unsub_org
<https://twitter.com/unsub_org>
