### ISSUE TITLE
all issn-ls should be in issn list

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/journalsdb#2]
http://journalsdb.org/journals/1879-3096

has 

"issn_l": "1879-3096",
"issns": [
"0167-7799"
],

but all issn_ls should be in issn list.  Thanks!

**Comment by caseydm** [comment]
I realized this is an issue related to the way we are filtering the list of raw ISSNs to what is in crossref. It affects a small portion of ISSNs and I'm working a fix.

**Comment by caseydm** [comment]
This is fixed.
