### ISSUE TITLE
Make this Elsevier publication

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/journalsdb#21]
Although it has a different society publisher, this is sold by Elsevier  so we'd like its publisher to be "Elsevier":

https://api.journalsdb.org/journals/0022-0302 
see https://www.sciencedirect.com/journal/journal-of-dairy-science

**Comment by caseydm** [comment]
Fixed! I updated the metadata as well. Will also run a script later to see if there are other journals with pricing but pointing to a different publisher.

**Comment by hpiwowar** [comment]
great, thanks!
