### ISSUE TITLE
incorrectly merged

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/journalsdb#22]
These journals are not the same:

https://www.journals.elsevier.com/chemical-engineering-research-and-design
https://www.journals.elsevier.com/process-safety-and-environmental-protection

but their ISSNs are both under
https://api.journalsdb.org/journals/0957-5820

Can you split them apart and fix?  Thanks!

**Comment by caseydm** [comment]
This is done. Split the journals, added metadata, and re-imported subscription and APC pricing so it is correctly mapped to each journal.

**Comment by hpiwowar** [comment]
yay thanks!
h

---

Heather Piwowar, cofounder

OurResearch <https://ourresearch.org/>: tools to make scholarly research
more open, connected, and reusable

follow at @researchremix <https://twitter.com/researchremix>,
@OurResearch_org <https://twitter.com/OurResearch_org>, @unpaywall,
<https://twitter.com/unpaywall> and @unsub_org
<https://twitter.com/unsub_org>
