### ISSUE TITLE
Questions about some ISSN's related to Sage

### ISSUE THREAD

**Issue by sckott** [ourresearch/journalsdb#32]
Hi Casey, Looking at some titles supposedly published with Sage, given to me by one of our library consortia. A few questions/comments. Sorry the below is a bit messy :) 

The goal here is for me to understand why certain titles are excluded from Unsub dashboards, reasons include: moved to Gold OA, not currently publishing, price not available, or new publisher. In particular the following is in relation to the new publisher category.

Here's a spreadsheet of the ISSN's excluded from a few Unsub dashboards. If there's an entry in the notes column I manually went to the website for the journal to inspect it. 

https://docs.google.com/spreadsheets/d/10Dw2MRkXzATua4fZh9EzXCY78TU6TioJ8ZG_KbGOK2E/edit#gid=0

In the "notes" column of the above spreadsheet I have the following categories:

- "clearly different publisher now": Great, new publisher, not Sage anymore, all good. 
- "articles are clearly on Sage websites": Some of these used to be with another publisher; some simply had "null" for publisher in JournalsDB. 
- there's a number of others with other notes based on looking at the publishers websites
- There's a bunch of ISSNs in the spreadsheet where the publisher is stated as not Sage (e.g., Libertas Academica, or American Educational Research Association, or Tsinghua University Press) in both JournalsDB and Crossref, but the title is clearly published with Sage. For subscription decision purposes for libraries, I imagine these cases where a title is published with Sage and a partner, subscriptions are done through Sage? E.g., subscription for an "American Educational Research Association" title is in Sage https://us.sagepub.com/en-us/nam/journal/educational-researcher#subscribe . In Unsub we use the publisher field from JournalsDB to determine whether to include a title in an Unsub dashboard or not, so it's clearly important what the publisher field has in it. I wonder if there's a way already in JournalsDB to determine the publisher where the subscription has to happen vs. the named publisher (that is simply a partner where the subscription does not occur). 

There's a column "crossref/journalsdb differ" that says whether publisher name differs in JournalsDB vs. Crossref

Note on Libertas Academica - Sage acquired this publisher back in 2016 https://sustainingknowledgecommons.org/category/publisher/libertas-academica/ Many of these titles are gold OA anyway, so would be excluded form Unsub dashboards due to that reason, so publisher isn't important, but publisher is important if the title is not Gold OA

**Comment by caseydm** [comment]
Hi @sckott I went through the spreadsheet and fixed all of the journals that I thought she be fixed. I added a column so you can see what changed. 

We have an imprint field in the database, but so far we have not exposed that through the API. We always assigned the "higher level" publisher to the publisher field in the API. So based on that I changed all of the libertas and AEAU to SAGE. I set the imprint appropriately in the database.

Take a look and let me know if you want anything else changed!

**Comment by sckott** [comment]
@caseydm 

- Missed one in the spreadsheet: publisher in https://api.journalsdb.org/journals/1178-2234 is still `null`, should be SAGE
- This title https://api.journalsdb.org/journals/2631-3103 has an empty array for `dois_by_issued_year` - crossref does have dois per year https://api.crossref.org/journals/2631-3103 - journal website https://journals.sagepub.com/home/WCC - Should have `dois_by_issued_year` and can `sample_dois` be filled in?
- Looks like ISSN 1539-6053 is correctly mapped on to https://api.journalsdb.org/journals/1529-1006, but on my end I have a  separate row in the database for ISSN 1539-6053 - whereas I'd expect just a row for ISSN 1529-1006. I don't see a row for ISSN 2160-0031, so that's good. Maybe delete row for ISSN 1539-6053?

**Comment by caseydm** [comment]
@sckott My replies are below.
> * Missed one in the spreadsheet: publisher in https://api.journalsdb.org/journals/1178-2234 is still `null`, should be SAGE

Done!

> * This title https://api.journalsdb.org/journals/2631-3103 has an empty array for `dois_by_issued_year` - crossref does have dois per year https://api.crossref.org/journals/2631-3103 - journal website https://journals.sagepub.com/home/WCC - Should have `dois_by_issued_year` and can `sample_dois` be filled in?

The problem with this one is that 2631-3103 should fall under the ISSN-L 2631-309X, which does have dois by year. So I went ahead and moved that ISSN under it as it should be.

> * Looks like ISSN 1539-6053 is correctly mapped on to https://api.journalsdb.org/journals/1529-1006, but on my end I have a  separate row in the database for ISSN 1539-6053 - whereas I'd expect just a row for ISSN 1529-1006. I don't see a row for ISSN 2160-0031, so that's good. Maybe delete row for ISSN 1539-6053?

I don't see an issue with this one. All of the relevant ISSNs appear to mapped together for the journal. Are you saying the ISSNs should point to separate journals? Because when I go to the journal web site I can see that 1539-6053 and 1529-1006 are linked together: https://journals.sagepub.com/home/psi. And apparently 2160-0031 is an older ISSN reference to that same journal. Let me know!

**Comment by sckott** [comment]
Thanks for those two fixes!

For the 3rd item: On our end, we do issn to issn-l mapping as you know. The way that looks is like this sql query  `select * from some_table where issn_l in ('1539-6053', '1529-1006', '2160-0031');`

Which results in 

issn_l | publisher | title | issn
-- | -- | -- | --
1539-6053 | SAGE | Psychological science in the public interest | 1539-6053
1529-1006 | SAGE | Psychological science in the public interest | 2160-0031
1529-1006 | SAGE | Psychological science in the public interest | 1539-6053
1529-1006 | SAGE | Psychological science in the public interest | 1529-1006

This table is essentially spreads each linking ISSN across X rows, where X is how many ISSNs map to that linking ISSN. Then we use the table to map ISSN to linking ISSN. 

So if a Unsub user uploads a counter file with the ISSN 1539-6053 then we'll map it to the linking ISSN 1539-6053, which is not correct. It should map to linking ISSN 1529-1006. 

We have that Xplenty job that moves data from journalsdb to the Unsub database, so perhaps it's something in there we need to fix? I'm not sure yet. Let me know if you have any ideas

**Comment by sckott** [comment]
One more - this one https://api.journalsdb.org/journals/2752-7646 should be SAGE - also, dois by year only has 2021 DOIs, but that's the case for Crossref as well. Any way to fix this?

**Comment by caseydm** [comment]
For the dois by year, @richard-orr will have to help with that. As far as I know we pull from crossref and if crossref does not have more data then I'm not sure what we do.

With ISSN 1539-6053, I think it is an issue with xplenty, or maybe something that needs to be resolved manually. It was probably wrong in journalsdb a while ago, but got corrected at some point. But that update didn't make it through xplenty and into your database properly. Everywhere I look in journalsdb, that ISSN is mapped to 1529-1006 like it should be.

I updated that last journal to SAGE so the publisher is correct.

**Comment by sckott** [comment]
Thanks Casey. I'll look into the 1539-6053 issue (xplenty, etc.)

@richard-orr thx in advance for looking into `dois_by_issued_year` for https://api.journalsdb.org/journals/2752-7646 - the only legitimate reason I can think of the missing DOIs is perhaps they changed ISSN between 2020 and 2021

**Comment by richard-orr** [comment]
@sckott  I think you're right; the journal rebranded and changed ISSNs: https://nafme.org/welcome-newly-rebranded-journal-general-music-education/

Articles from before 2021 like https://api.crossref.org/v1/works/http://dx.doi.org/10.1177/1048371319834921 have the old ISSN and are counted here: https://api.journalsdb.org/journals/1048-3713

**Comment by sckott** [comment]
thanks @richard-orr ! I guess I could have googled that 😊

**Comment by sckott** [comment]
one more:

- https://api.journalsdb.org/journals/0013-189X title should be `Educational researcher` not `Educational researcher :`

**Comment by caseydm** [comment]
> one more:
> 
> * https://api.journalsdb.org/journals/0013-189X title should be `Educational researcher` not `Educational researcher :`

This is fixed. I searched and found 402 journals had that same pattern with a ":" at the end. So I went ahead and fixed all of them.

I guess we need to merge these together right?
https://api.journalsdb.org/journals/2752-7646
https://api.journalsdb.org/journals/1048-3713

**Comment by sckott** [comment]
Thanks for fixing that one and all those other 400ish! 

> I guess we need to merge these together right?

I would think so? I don't know if you have a way you deal with this already? Just thinking logically it makes sense to merge b/c a reader or a subscriber of the old title and ISSN isn't going to suddenly not read or subscribe b/c of the title or ISSN change, so its really the same journal still

**Comment by caseydm** [comment]
Ok those two journals are merged together. https://api.journalsdb.org/journals/2752-7646

It may take a day or two for the DOI counts to be updated properly.

**Comment by sckott** [comment]
thanks!
