### ISSUE TITLE
Questions about some ISSN's related to Taylor & Francis

### ISSUE THREAD

**Issue by sckott** [ourresearch/journalsdb#33]
Hi Casey, Same thing here as in #32 but for T&F

spreadsheet: https://docs.google.com/spreadsheets/d/1tPNdcaBUleGy8TGJNLa-okj6OW83GiHCbQl87TuYQac/edit?pli=1#gid=916071260

These ISSNs are those excluded from Unsub dashboards for various reasons. 

There's a column "crossref/journalsdb differ" that says whether publisher name differs in JournalsDB vs. Crossref. And the next column is "correct?", which is only filled in if the "crossref/journalsdb differ" column has a "yes" in it. If the "correct?" column is filled in, then I've filled in the "notes" column with notes about the publisher and related issues after looking up the ISSN. 

In the "notes" column there's various issues. 

- JournalsDB has the correct publisher and Crossref has the wrong publisher.
- JournalsDB has a publisher that is correct, but is I think an imprint of a larger publisher. For Unsub, we'd need to know the parent publisher, not the imprint
- In most of these cases the publisher is `null` for JournalsDB, and I've looked up the correct publisher, which is T&F in most cases. For these ISSN's I also noted whether they are not publishing anymore, if they're under a different ISSN in Crossref, and if the publisher needs to be changed to something other than T&F.

**Comment by caseydm** [comment]
Hi @sckott. Similar to the other issue I updated all of the appropriate publishers and status, as well as the one title that had an inaccurate journal title.

**Comment by sckott** [comment]
Thanks!

- Landes Bioscience: this publisher was [acquired by T&F in 2014](https://en.wikipedia.org/wiki/Landes_Bioscience). Seems like a lot of these journals are not published anymore, so would be excluded from Unsub dashboards through that route anyway. At least some of these are still published though, and so probably best to change these to T&F
- National Inquiry Services Center (NISC): these titles are published on behalf of the society NISC by T&F. Change to T&F.

**Comment by caseydm** [comment]
> * Landes Bioscience: this publisher was [acquired by T&F in 2014](https://en.wikipedia.org/wiki/Landes_Bioscience). Seems like a lot of these journals are not published anymore, so would be excluded from Unsub dashboards through that route anyway. At least some of these are still published though, and so probably best to change these to T&F
> * National Inquiry Services Center (NISC): these titles are published on behalf of the society NISC by T&F. Change to T&F.

All of these are changed in the database.

**Comment by sckott** [comment]
thanks!

**Comment by sckott** [comment]
@caseydm a few more T&F items/questions

- https://api.journalsdb.org/journals/2692-9953 appears to be still publishing, https://www.tandfonline.com/loi/usac21 but JDB has empty array for `dois_by_issued_year`, and status of "unknown"
- This ones a bit odd: https://api.journalsdb.org/journals/0040-2826 First, it's sample dois all resolve to land at https://www.tandfonline.com/journals/zela20 Tellus A: Dynamic Meteorology and Oceanography. Second, the journal is still publishing https://www.tandfonline.com/loi/zelb20 even though the latest year in `dois_by_issued_year` is 2010. 
- perhaps this ISSN https://api.journalsdb.org/journals/0373-7934 should be an alias for https://api.journalsdb.org/journals/0001-5385 ?  `0373-7934` is the online ISSN on the publishers website at least

**Comment by sckott** [comment]
a few more

- https://api.journalsdb.org/journals/1545-0430 should be T&F
- https://api.journalsdb.org/journals/1026-7735 should be T&F
- https://api.journalsdb.org/journals/1026-7921 should be T&F
- https://api.journalsdb.org/journals/0148-3927 should be T&F
- https://api.journalsdb.org/journals/1026-5473 should be T&F

**Comment by caseydm** [comment]
Those are updated!

**Comment by sckott** [comment]
Thanks for the fixes for the 5 journals in https://github.com/ourresearch/journalsdb/issues/33#issuecomment-1013570124 - Did you get a chance to look at the 3 journals in https://github.com/ourresearch/journalsdb/issues/33#issuecomment-1013515225 ?

**Comment by caseydm** [comment]
> Did you get a chance to look at the 3 journals in [#33 (comment)](https://github.com/ourresearch/journalsdb/issues/33#issuecomment-1013515225) ?

Oh shoot no I did not. Will do that shortly.

**Comment by caseydm** [comment]
I see the issue with the first one (https://api.journalsdb.org/journals/2692-9953). If you scroll down on [this page](https://www.tandfonline.com/action/journalInformation?journalCode=usac21) it says that the journal was renamed in 2021. So they gave it new ISSNs. The old ISSNs are [here](https://api.journalsdb.org/journals/1072-0162) and have all of the data you would expect to be associated with the journal.

This situation is tricky because the right thing to do is to move the two ISSNs and all the data under 1072-0162 under the new ISSN of 2692-9953. But it takes a while for DOI counts and open access data to catch up when doing that. It would be cleaner to simply move the new ISSNs under the old one. I think I will fix it the right way but we may lose the DOI counts and open access data for a bit.

**Comment by sckott** [comment]
Thanks for the explanation. Your solution makes sense

**Comment by caseydm** [comment]
> * https://api.journalsdb.org/journals/2692-9953 appears to be still publishing, https://www.tandfonline.com/loi/usac21 but JDB has empty array for `dois_by_issued_year`, and status of "unknown"

I merged the old ISSNs into the new one: https://api.journalsdb.org/journals/2692-9953. I was able to merge subscription data and metadata as well. But will need to wait for an update to see DOI counts and open access data.

> * This ones a bit odd: https://api.journalsdb.org/journals/0040-2826 First, it's sample dois all resolve to land at https://www.tandfonline.com/journals/zela20 Tellus A: Dynamic Meteorology and Oceanography. Second, the journal is still publishing https://www.tandfonline.com/loi/zelb20 even though the latest year in `dois_by_issued_year` is 2010.

I made some improvements to these two (title for one of them was incorrect.). The sample DOIs are pointing to the right location. I'm not sure what's going on with the DOI counts. Maybe @richard-orr can help with that?

> * perhaps this ISSN https://api.journalsdb.org/journals/0373-7934 should be an alias for https://api.journalsdb.org/journals/0001-5385 ?  `0373-7934` is the online ISSN on the publishers website at least

This is done!

**Comment by sckott** [comment]
Thanks Casey!
