### ISSUE TITLE
Journal of Applied Corporate Finance

### ISSUE THREAD

**Issue by sckott** [ourresearch/journalsdb#35]
There's two, or maybe just one, issue with this specific Wiley title. 

## issn's
In JournalsDB we have https://api.journalsdb.org/journals/1936-8216 - in that response we have ISSN's 1936-8216 and 1745-6622, but not 1078-1196

In Crossref https://api.crossref.org/journals/1936-8216 is not found
It is in Crossref under https://api.crossref.org/journals/1078-1196 or https://api.crossref.org/journals/1745-6622

I'm not sure if Crossref is off here or if JournalsDB is? That is, shouldn't Crossref have the linking ISSN? or am I misunderstanding something?

## currently publishing / dois_by_issued_year

JournalsDB has only one doi issued in 2015 for this title. Whereas Crossref has DOIs issued all the way up through 2021. Perhaps this is linked to the ISSNs issue discussed above?

AFAICT, it's this false positive for not currently publishing that for one Unsub user means this title is missing from their dashboard

**Comment by caseydm** [comment]
This is fixed: https://api.journalsdb.org/journals/1078-1196. All of the related ISSNs point to a single ISSN-L now.

**Comment by sckott** [comment]
Awesome, thanks very much!
