### ISSUE TITLE
larger publishers publishing on behalf of smaller societies

### ISSUE THREAD

**Issue by sckott** [ourresearch/journalsdb#36]
I've touched on this in other issues I think, but wanted to talk about this directly. 

There's a number of cases where the publisher listed in JournalsDB and Crossref for an ISSN is some society like the "London Mathematical Society" - But the journal is clearly handled by a larger publisher. 

In this case https://api.journalsdb.org/journals/0024-6107 "Journal of the London Mathematical Society" you subscribe to the journal on the Wiley website https://londmathsoc.onlinelibrary.wiley.com/toc/14697750/2006/73/1 

For the purposes of Unsub, I'd think it would make sense for this title to be included in their Wiley dashboard, rather than their  London Mathematical Society dashboard. But maybe that's not right.

You forwarded me the email covering standardizing across publisher imprints, so that's related here, but I think publishing on behalf of societies is different from imprints, yes?

How have you dealt with this so far with Elsevier? I imagine it has come up.

**Comment by caseydm** [comment]
I have dealt with this but have not really discussed it too much. I think if a society has Wiley publish the journal (that's how you can read article, subscribe, etc) then the publisher in journalsdb is Wiley.  I went ahead and changed all seven of the journals we had listed for that publisher over to Wiley. Let me know if you find any more like that!

**Comment by sckott** [comment]
Thanks Casey! I'll let you know as I find more of these

I talked to Jason about this issue of society publishers. He said to treat it the same as imprints. To me that means changing the publisher to e.g., Wiley instead of the society it publishes on behalf of. In the Unsub backend, we don't need to know about imprint vs. society publisher - we just look at the publisher field, which has to match the current Unsub package in question. 

However, there are the two journalsdb fields related to this: the unexposed imprint data you maintain and the exposed field `is_society_journal` - I think it makes sense to keep maintaining those metadata as they are. 

AFAICT it seems like `is_society_journal` isn't always populated. Is that right? We don't use that field for logic in Unsub, but it is exposed in Unsub dashboards, so it would be helpful for it to be fully populated at some point if feasible.

**Comment by caseydm** [comment]
Ok sounds like we are on the same page. As for `is_society_journal`, you are right that it is not always populated. We only populated that field for the top five publishers. Of those, around 3,900 journals have it marked as true. 6,600 are marked as false and 4,000 are null. We need to go through and review the null values as I looked through and found a couple that were society journals.
