### ISSUE TITLE
Some Wiley titles

### ISSUE THREAD

**Issue by sckott** [ourresearch/journalsdb#37]
- https://api.journalsdb.org/journals/0892-6638 Can you change to publisher Wiley? It's published on behalf of the society "Federation of American Society for Experimental Biology"
- https://api.journalsdb.org/journals/0012-9682 Can you change to publisher Wiley? It's published on behalf of the society "The Econometric Society"
- https://api.journalsdb.org/journals/1538-6341 Can you change to publisher Wiley? It's published on behalf of the "The University of Ottawa". However, Crossref still has https://api.crossref.org/journals/1538-6341 "Guttmacher Institute" as the publisher, which journalsdb also has. Googled and can't find any evidence that The University of Ottawa is affiliated, other than on the Wiley site for the journal.

**Comment by caseydm** [comment]
These are all changed.

**Comment by sckott** [comment]
thank you!
