### ISSUE TITLE
Fix title 

### ISSUE THREAD

**Issue by sckott** [ourresearch/journalsdb#38]
This issn https://api.journalsdb.org/journals/0305-1862 has the title "Child" 

Whereas I think it should be "Child: Care, Health and Development"

Crossref has https://api.crossref.org/journals/0305-1862 "Child Care, Health and Development", without the colon, but I think they have it wrong (colon should be there)

**Comment by caseydm** [comment]
This is done. I agree with your title, since that matches what is on the publisher web page.

**Comment by sckott** [comment]
thanks!
