### ISSUE TITLE
Add sample DOIs to API response

### ISSUE THREAD

**Issue by caseydm** [ourresearch/journalsdb#4]
Want to add 3 sample DOI links in the API response (https://doi.org/DOI ie clickable)

**Comment by caseydm** [comment]
This is added now.

http://api.journalsdb.org/journals/1555-9475

**Comment by hpiwowar** [comment]
Yay I love it, thanks!
h

---

Heather Piwowar, cofounder

Our Research <https://ourresearch.org/>: tools to make scholarly research
more open, connected, and reusable
follow at @researchremix <https://twitter.com/researchremix>, @our_research
<https://twitter.com/our_research>, @unpaywall,
<https://twitter.com/unpaywall> and @unsub_org
<https://twitter.com/unsub_org>
