### ISSUE TITLE
Springer Nature issues

### ISSUE THREAD

**Issue by sckott** [ourresearch/journalsdb#42]
Same drill as w/ the other 3 publishers, this time with Springer Nature

Spreadsheet https://docs.google.com/spreadsheets/d/1FS6FOgUsV4F8JRPbHU7i27mO870nWQJDBN8Cjxd7Dc4/edit#gid=0

Filter column journalsdb == 1 for columns where I think a change should be made in journalsdb. To highlight a few of the bigger ones:

- Allerton Press: a bunch of titles (44) have Allerton Press as the publisher. Crossref has the same publisher for these. However, these titles are all housed with Springer. I don't see any subscription information on the websites for these titles other than "institutional subscription". We do have subscription prices for the few titles are checked under Allerton Press, but I'm not sure who you'd subscribe through (Springer or Allerton). Thoughts?
- Pleiades Publishing: marked a bunch of titles (127) to ask you about from Pleiades. They have on their website "Subscription is available from the distributor of the English-language journals, Springer Nature" - so for Unsub purposes, i think we want Springer Nature b/c that's how the subscription is done. Do you agree?
- As with the other publishers (Wiley, SAGE, TF) there's a number of society publishers that have Springer publish their journals
- There's 46 titles where publisher is `null`
- There's 2 titles copublished with Zhejiang University Press that I think should be changed to Springer

**Comment by sckott** [comment]
Thanks @caseydm for all the fixes !

**Comment by sckott** [comment]
There's still 3 ISSN's with `null` publisher's:

- https://api.journalsdb.org/journals/0303-9692
- https://api.journalsdb.org/journals/1124-1861
- https://api.journalsdb.org/journals/1774-6701

Can those be fixed to have Springer Nature for publisher?

**Comment by caseydm** [comment]
> Can those be fixed to have Springer Nature for publisher?

Sorry about that! Those are updated now too.

**Comment by sckott** [comment]
thanks very much
