### ISSUE TITLE
Fix titles with "ISSN" in their name

### ISSUE THREAD

**Issue by sckott** [ourresearch/journalsdb#44]
https://api.journalsdb.org/journals/1047-8310

Strip "Issn: 1047-8310 " out of  "Issn: 1047-8310 The Journal Of High Technology Management Research"

**Comment by sckott** [comment]
The above title is in Elsevier so is more important as it would affect current Unsub users. 

I found a few more with ISSN in their title:

- 2471-822X: Journal of Virology and Emerging Diseases ( ISSN 2471-822X )
- 2239-0243: UNKNOWN_TITLE/issn=2239-0243
- 2724-3346: UNKNOWN_TITLE/issn=2724-3346

**Comment by caseydm** [comment]
These are fixed.

**Comment by sckott** [comment]
thanks!
