### ISSUE TITLE
Get accurate DOI counts in database

### ISSUE THREAD

**Issue by caseydm** [ourresearch/journalsdb#7]
Work with Richard to pull accurate DOI counts (total and by year) from unpaywall. Try to use xplenty if feasible.

**Comment by caseydm** [comment]
This is working now. Richard created a job in xplenty that is updating all DOI counts once per day. The journalsdb API is now using that data rather than the crossref API.

**Comment by hpiwowar** [comment]
great, thanks!

---

Heather Piwowar, cofounder

Our Research <https://ourresearch.org/>: tools to make scholarly research
more open, connected, and reusable
follow at @researchremix <https://twitter.com/researchremix>, @our_research
<https://twitter.com/our_research>, @unpaywall,
<https://twitter.com/unpaywall> and @unsub_org
<https://twitter.com/unsub_org>
